<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHYTuaDR\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHYTuaDR/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHYTuaDR.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHYTuaDR\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHYTuaDR\App_KernelProdContainer([
    'container.build_hash' => 'HYTuaDR',
    'container.build_id' => '79f730e2',
    'container.build_time' => 1738199658,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHYTuaDR');
