<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book extends \App\Entity\Book implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'author' => [parent::class, 'author', null],
        "\0".parent::class."\0".'createdBy' => [parent::class, 'createdBy', null],
        "\0".parent::class."\0".'genre' => [parent::class, 'genre', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageFilename' => [parent::class, 'imageFilename', null],
        "\0".parent::class."\0".'pages' => [parent::class, 'pages', null],
        "\0".parent::class."\0".'reviews' => [parent::class, 'reviews', null],
        "\0".parent::class."\0".'summary' => [parent::class, 'summary', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        'author' => [parent::class, 'author', null],
        'createdBy' => [parent::class, 'createdBy', null],
        'genre' => [parent::class, 'genre', null],
        'id' => [parent::class, 'id', null],
        'imageFilename' => [parent::class, 'imageFilename', null],
        'pages' => [parent::class, 'pages', null],
        'reviews' => [parent::class, 'reviews', null],
        'summary' => [parent::class, 'summary', null],
        'title' => [parent::class, 'title', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
