<?php

namespace ContainerGj6w5Ha;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PZXUkcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P_zXUkc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P_zXUkc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'review' => ['privates', '.errored..service_locator.P_zXUkc.App\\Entity\\Review', NULL, 'Cannot autowire service ".service_locator.P_zXUkc": it needs an instance of "App\\Entity\\Review" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'review' => 'App\\Entity\\Review',
            'entityManager' => '?',
        ]);
    }
}
