<?php

namespace ContainerGj6w5Ha;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RNIzZucService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RNIzZuc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RNIzZuc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.aSfeIIj.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.ImjIA.9.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReviewController::index' => ['privates', '.service_locator.E.y3d6j.App\\Controller\\ReviewController::index()', 'getReviewControllerindexService', true],
            'App\\Controller\\ReviewController::new' => ['privates', '.service_locator.3eJdMmM.App\\Controller\\ReviewController::new()', 'getReviewControllernewService', true],
            'App\\Controller\\ReviewController::show' => ['privates', '.service_locator.HRtw6RZ.App\\Controller\\ReviewController::show()', 'getReviewControllershowService', true],
            'App\\Controller\\ReviewController::edit' => ['privates', '.service_locator.P_zXUkc.App\\Controller\\ReviewController::edit()', 'getReviewControllereditService', true],
            'App\\Controller\\ReviewController::delete' => ['privates', '.service_locator.P_zXUkc.App\\Controller\\ReviewController::delete()', 'getReviewControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.aSfeIIj.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.ImjIA.9.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReviewController:index' => ['privates', '.service_locator.E.y3d6j.App\\Controller\\ReviewController::index()', 'getReviewControllerindexService', true],
            'App\\Controller\\ReviewController:new' => ['privates', '.service_locator.3eJdMmM.App\\Controller\\ReviewController::new()', 'getReviewControllernewService', true],
            'App\\Controller\\ReviewController:show' => ['privates', '.service_locator.HRtw6RZ.App\\Controller\\ReviewController::show()', 'getReviewControllershowService', true],
            'App\\Controller\\ReviewController:edit' => ['privates', '.service_locator.P_zXUkc.App\\Controller\\ReviewController::edit()', 'getReviewControllereditService', true],
            'App\\Controller\\ReviewController:delete' => ['privates', '.service_locator.P_zXUkc.App\\Controller\\ReviewController::delete()', 'getReviewControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::new' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReviewController::index' => '?',
            'App\\Controller\\ReviewController::new' => '?',
            'App\\Controller\\ReviewController::show' => '?',
            'App\\Controller\\ReviewController::edit' => '?',
            'App\\Controller\\ReviewController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:new' => '?',
            'App\\Controller\\BookController:show' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReviewController:index' => '?',
            'App\\Controller\\ReviewController:new' => '?',
            'App\\Controller\\ReviewController:show' => '?',
            'App\\Controller\\ReviewController:edit' => '?',
            'App\\Controller\\ReviewController:delete' => '?',
        ]);
    }
}
