<?php

namespace ContainerHYTuaDR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BookRepository' shared autowired service.
     *
     * @return \App\Repository\BookRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BookRepository'] = new \App\Repository\BookRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
