<?php

namespace ContainerHYTuaDR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookVoterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\Voter\BookVoter' shared autowired service.
     *
     * @return \App\Security\Voter\BookVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Security\\Voter\\BookVoter'])) {
            return $container->privates['App\\Security\\Voter\\BookVoter'];
        }

        return $container->privates['App\\Security\\Voter\\BookVoter'] = new \App\Security\Voter\BookVoter($a);
    }
}
