<?php

namespace ContainerHYTuaDR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReview2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.P_zXUkc.App\Entity\Review' shared service.
     *
     * @return \App\Entity\Review
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.P_zXUkc": it needs an instance of "App\\Entity\\Review" but this type has been excluded in "config/services.yaml".');
    }
}
