<?php

namespace ContainerHYTuaDR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.P_zXUkc.App\Controller\ReviewController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.P_zXUkc'] ?? $container->load('get_ServiceLocator_PZXUkcService'));

        if (isset($container->privates['.service_locator.P_zXUkc.App\\Controller\\ReviewController::edit()'])) {
            return $container->privates['.service_locator.P_zXUkc.App\\Controller\\ReviewController::edit()'];
        }

        return $container->privates['.service_locator.P_zXUkc.App\\Controller\\ReviewController::edit()'] = $a->withContext('App\\Controller\\ReviewController::edit()', $container);
    }
}
