<?php

namespace ContainerHYTuaDR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ReviewRepository' shared autowired service.
     *
     * @return \App\Repository\ReviewRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ReviewRepository'] = new \App\Repository\ReviewRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
