<?php

namespace ContainerHYTuaDR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SecurityFormType' shared autowired service.
     *
     * @return \App\Form\SecurityFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SecurityFormType'] = new \App\Form\SecurityFormType();
    }
}
