<?php

namespace ContainerC2aF2uh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ImjIA.9.App\Controller\BookController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ImjIA.9.App\\Controller\\BookController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.ImjIA.9.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.ImjIA.9": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'reviewRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'reviewRepository' => 'App\\Repository\\ReviewRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\BookController::show()', $container);
    }
}
