<?php

namespace ContainerC2aF2uh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.52LSSp5.App\Controller\BookController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.52LSSp5'] ?? $container->load('get_ServiceLocator_52LSSp5Service'));

        if (isset($container->privates['.service_locator.52LSSp5.App\\Controller\\BookController::edit()'])) {
            return $container->privates['.service_locator.52LSSp5.App\\Controller\\BookController::edit()'];
        }

        return $container->privates['.service_locator.52LSSp5.App\\Controller\\BookController::edit()'] = $a->withContext('App\\Controller\\BookController::edit()', $container);
    }
}
